spring:
  application:
    name: agendamento-com-cobranca-pix
  datasource:
    url: jdbc:postgresql://localhost:5432/agendamento
    username: agendamento
    password: agendamento
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

asaas:
  base-url: https://api-sandbox.asaas.com/v3
  api-key: ${ASAAS_API_KEY:}
  webhook-token: ${ASAAS_WEBHOOK_TOKEN:}

agendamento:
  expiracao:
    intervalo-ms: 60000
